import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);


import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const OutfitFonts = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFonts.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><main className="maxd-w-7xl mx-auto"><Navbar/>{children}<Footer/></main></body>
    </html>
  );
}
